### ISSUE TITLE
syck seems to not work on ruby 2.2.0p0 (2014-12-25 revision 49005) [i686-linux] 

### ISSUE THREAD

**Issue by shevegen** [tenderlove/syck#9]
Hello,

This is an error possibly on ruby 2.2.0p0.
syck works perfectly fine on ruby 2.1.5 for me.

The error I get is when I try to do this here:

    YAML::ENGINE.yamler

I used this before to set syck.

When I do this, though, I immediately get this error:

    NameError: uninitialized constant Psych::Syck::ENGINE

Both psych and syck were required before I tried the above.

I assume something has changed in between these two ruby
versions but I am not quite sure how to trace back this error.

Thanks.

**Comment by fredv** [comment]
Hi Aaron @tenderlove,
this seems to be because of the removal of YAML::ENGINE in psych. (see https://github.com/tenderlove/psych/blob/24ff7855ca2f62e59fc951fa30b225f42369c2a2/CHANGELOG.rdoc, Sun May 25 11:35:41 2014 Zachary Scott <e@zzak.io> * test/psych/*: YAML::ENGINE was removed in [Bug #8344])

Is there an alternative way? Maybe the constant overwriting part could be optional or another version switch included?

This should be a legacy problem, for our case it's about handling different parsing behavior of psych and syck (I think I remember some cases where syck can parse fairly valid structures from technically invalid YAML ... which is awkward on its own I guess).

We will work around this by not using syck in this case as fallback, I think.

Thank you for putting together both libraries!

**Comment by jcabasc** [comment]
Is there any update on this? Still having the same with ruby-2.2.0 or greater.

**Comment by hsbt** [comment]
Hi, If you are submit a patch of this issu, I will merge it.

**Comment by dbackeus** [comment]
+1

**Comment by ccutrer** [comment]
You should be able to check `YAML.name`. In regular ruby 2.2, you get `"Psych"`, but with the syck gem you get `"Syck"`.

**Comment by jjgh** [comment]
So, is it still possible to use the "syck" engine with Ruby 2.2?
I purposedly had used it in some old code in order to avoid dumping to binary format...

I think I will be in for a big refactor if I can't just make it work with "syck" ... ?

**Comment by GCinellu** [comment]
+ 1

**Comment by courtenay** [comment]
this appears to be broken again on 2.3.x

```
irb
irb(main):001:0> RUBY_VERSION
=> "2.3.4"
irb(main):002:0> require 'yaml'
=> true
irb(main):003:0> require 'syck'
=> true
irb(main):004:0> YAML::ENGINE
NameError: uninitialized constant Syck::ENGINE
	from (irb):4
	from /Users/courtenay/.rbenv/versions/2.3.4/bin/irb:11:in `<main>'
```

looking at the code for engine_manager should be possible to just require that, but..

```
irb(main):006:0> require 'yaml/engine_manager'
/Users/courtenay/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/syck-1.2.0/lib/yaml/engine_manager.rb:70: warning: already initialized constant Syck::ENGINE
/Users/courtenay/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/syck-1.2.0/lib/yaml/engine_manager.rb:49: warning: previous definition of ENGINE was here
=> true
irb(main):007:0> YAML::ENGINE
=> #<Syck::EngineManager:0x007fb4d993cc78 @yamler=nil>
irb(main):008:0> YAML::ENGINE.yamler
=> nil
irb(main):009:0> YAML::ENGINE.yamler = 'syck'
NameError: constant Syck::Object::YAML not defined
	from /Users/courtenay/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/syck-1.2.0/lib/yaml/engine_manager.rb:34:in `remove_const'
	from /Users/courtenay/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/syck-1.2.0/lib/yaml/engine_manager.rb:34:in `yamler='
	from /Users/courtenay/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/syck-1.2.0/lib/yaml/engine_manager.rb:33:in `class_eval'
	from /Users/courtenay/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/syck-1.2.0/lib/yaml/engine_manager.rb:33:in `yamler='
	from (irb):9
	from /Users/courtenay/.rbenv/versions/2.3.4/bin/irb:11:in `<main>'
```

it appears that this fixes it _somewhat_ in engine_manager

```
-      Object.class_eval <<-eorb, __FILE__, __LINE__ + 1
+     ::Object.class_eval <<-eorb, __FILE__, __LINE__ + 1

```

i'm not sure if this is right though :)

**Comment by mikhailov** [comment]
is there a plan to get it working with Ruby 2.3.5?

**Comment by nuritnt** [comment]
any news on this?

**Comment by hsbt** [comment]
Nothin. I always welcome your patch.

**Comment by intrip** [comment]
> is there a plan to get it working with Ruby 2.3.5?

It works with Ruby 2.3.5, when you 'require "syck"' the YAML parser [is automatically replaced by syck](https://github.com/ruby/syck/blob/f0cb457c2de71d9cfb41f65ae47b3f3fdddacd56/lib/syck.rb#L11-L16).
